=== bryansaayman/IDSProject/productsSchema.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="products" type="ProductsType"/>
	
	<xsd:complexType name="ProductsType">
		<xsd:sequence>
			<xsd:element name="product" type="ProductDetails" minOccurs="0"
			maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="ProductDetails">
		<xsd:sequence>
			<xsd:element name="category" type="xsd:string"/>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="price" type="xsd:double"/>
			<xsd:element name="quantity" type="xsd:integer"/>
			<xsd:element name="size" type="xsd:string"/>
			<xsd:element name="photo" type="xsd:string"/>
		</xsd:sequence>
		
		<xsd:attribute name="id" type="idType"/>
	</xsd:complexType>
	
	<xsd:simpleType name="idType">
		<xsd:restriction base="xsd:ID">
			<xsd:pattern value="[a-z]{2}[0-9]{1}"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== bryansaayman/IDSProject/products - Copy.xml
<?xml version="1.0" encoding="UTF-8"?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="productsSchema.xsd"><product id="id1"><category>Meat</category><name>Chicken</name><price>1</price><quantity>1</quantity><size>medium</size><photo>Uploads/potato.jpg</photo></product><product id="id2"><category>Vegetable</category><name>Carrot</name><price>1</price><quantity>1</quantity><size>small</size><photo>Uploads/potato.jpg</photo></product><product id="id3"><category>Fruit</category><name>Apple</name><price>1</price><quantity>1</quantity><size>small</size><photo>Uploads/potato.jpg</photo></product><product id="id4"><category>Fish</category><name>Hake</name><price>1</price><quantity>1</quantity><size>medium</size><photo>Uploads/potato.jpg</photo></product><product id="id5"><category>Carbohydrates</category><name>Bread</name><price>1</price><quantity>1</quantity><size>small</size><photo>Uploads/potato.jpg</photo></product></products>
